datasæt:
  batch_size: 512
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
Downstream:
  variant1:
    epoker: 200
    model:
      hovedtype: klogt
      gamma: 0.95
      lr: 1.0e-03
      step_size: 1
      ønsket_lr: 1.0e-03
      opvarmningsperiode: 1
      predicted_attribute: 1
      weight_decay: 1.0e-03
    seed: 42
rygradtype: visnet