cutoff: 5.0
hidden_channels: 64
lmax: 1
maskeringsandel: null
max_num_neighbors: 32
max_z: 100
num_heads: 8
num_layers: 12
num_rbf: 32
trainable_rbf: false
trainable_vecnorm: false
vecnorm_type: null
vertex: false