debug: True
delmængdestørrelse: 1.0
fordeling: [0.85, 0.0125, 0.085, 0.0125, 0.04]
batch_size: 1
num_workers: 0
epoker_selvtræn: 1
epoker_efterfølgende: 1
frys_rygrad: True
lr: 0.1
step_size: 5
gamma: 0.9