datasæt:
  batch_size: 256
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
  n_trin: 5
  spænd:
    - 10
    - 500
  val_reduced: false
downstream:
  check_val_every_n_epoch: 10
  epoker: 200
  min_delta: 0.1
  model:
    hovedtype: klogt
    gamma: 0.1
    lr: 1.0e-02
    step_size: 5000
    ønsket_lr: 1.0e-02
    opvarmningsperiode: 1
    predicted_attribute: 1
  patience: 20
rygradtype: visnet
selvvejledt:
  check_val_every_n_epoch: 1
  epoker: 50
  min_delta: 0.001
  model:
    hovedtype: klogt
    gamma: 0.1
    lambdaer:
      lokalt: 1000
      globalt: 1
    lr: 1.0e-08
    step_size: 15
    ønsket_lr: 1.0e-06
    opvarmningsperiode: 3
    noise_fra: -2
    noise_til: 1
    n_noise_trin: 10
    log_gradient: false
  patience: 20
udgaver:
  - med
  - uden
temperaturer:
  - frossen
