datasæt:
  batch_size: 256
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
  n_trin: 3
  spænd:
    - 10
    - 500
  val_reduced: true
downstream:
  optøet:
    check_val_every_n_epoch: 80
    epoker: 800
    min_delta: 0.1
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 3.0e-03
      step_size: 1
      ønsket_lr: 3.0e-03
      opvarmningsperiode: 1
      predicted_attribute: 1
    patience: 20
  frossen:
    check_val_every_n_epoch: 5
    epoker: 100
    min_delta: 0.1
    model:
      hovedtype: klogt
      gamma: 0.95
      lr: 1.0e-02
      step_size: 1
      ønsket_lr: 1.0e-02
      opvarmningsperiode: 1
      predicted_attribute: 1
    patience: 20
rygradtype: visnet
udgaver:
  - med
temperaturer:
  - optøet
selv_ckpt_path: s194255/afhandling/model-4ci6vjyd:v0
kørselsid: null
