selvvejledt:
  model:
    lr: 0.00001
    step_size: 20
    gamma: 0.5
    lambdaer: null
  hoved:
    atomref: null
    max_z: 100
    reduce_op: sum
    mean: 0.0
    std: 1.0
  epoker: 50
  min_delta: 0.001
  patience: 3
downstream:
  model:
    lr: 0.00001
    step_size: 20
    gamma: 0.5
  hoved:
    out_channels: 1
    reduce_op: "sum"
  epoker: 100
  min_delta: 0.1
  patience: 3
datasæt:
  debug: False
  delmængdestørrelse: 1.0
  fordeling: [0.4675, 0.0125, 0.4675, 0.0125, 0.04]
  batch_size: 128
  num_workers: 4
rygrad:
  lmax: 1
  vecnorm_type: null
  trainable_vecnorm: false
  num_heads: 8
  num_layers: 6
  num_rbf: 32
  trainable_rbf: false
  cutoff: 5.0
  max_num_neighbors: 32
  vertex: false
  hidden_channels: 128
  max_z: 100
  maskeringsandel: null
trin: 10
frys_rygrad: False