datasæt:
  batch_size: 32
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
  n_trin: 1
  spænd:
    - 100
    - 150
downstream:
  epoker: 150
  min_delta: 0.1
  model:
    hovedtype: dumt
    gamma: 0.1
    lr: 1.0e-08
    step_size: 40
    ønsket_lr: 1.0e-06
    opvarmningsperiode: 2
    predicted_attribute: 1
  patience: 20
rygrad:
  cutoff: 5.0
  hidden_channels: 512
  lmax: 1
  maskeringsandel: null
  max_num_neighbors: 32
  max_z: 100
  num_heads: 8
  num_layers: 6
  num_rbf: 32
  trainable_rbf: false
  trainable_vecnorm: false
  vecnorm_type: null
  vertex: false
selvvejledt:
  epoker: 15
  hoved:
    atomref: null
    max_z: 100
    mean: 0.0
    reduce_op: sum
    std: 1.0
  min_delta: 0.001
  model:
    hovedtype: klogt
    gamma: 0.1
    lambdaer: null
    lr: 1.0e-06
    step_size: 500
    ønsket_lr: 1.0e-05
    opvarmningsperiode: 3
    noise_fra: -1
    noise_til: 1
    n_noise_trin: 2
    log_gradient: false
  patience: 20
udgaver:
  - med
  - uden
temperaturer:
  - frossen
  - optøet