datasæt:
  batch_size: 32
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 3
  n_train: 2000
downstream:
  epoker: 150
  hoved:
    num_layers: 2
    reduce_op: sum
  model:
    gamma: 0.1
    lr: 1.0e-06
    opvarmningsperiode: 10
    predicted_attribute: 1
    step_size: 30
    ønsket_lr: 1.0e-04
rygrad:
  cutoff: 5.0
  hidden_channels: 512
  lmax: 1
  maskeringsandel: null
  max_num_neighbors: 32
  max_z: 100
  num_heads: 16
  num_layers: 6
  num_rbf: 32
  trainable_rbf: false
  trainable_vecnorm: false
  vecnorm_type: null
  vertex: false
frys_rygrad: false