datasæt:
  batch_size: 512
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 2
  n_trin: 5
  spænd:
    - 30
    - 500
  val_reduced: true
  name: QM9
Downstream:
  optøet:
    check_val_every_n_epoch: 10
    epoker: 300
    steps: -1
    gradient_clipping: null
    model:
      hovedtype: klogt
      gamma: 0.98
      lr: 4.0e-03
      step_size: 1
      ønsket_lr: 2.5e-04
      opvarmningsperiode: 100
      frossen_opvarmningsperiode: 100
      predicted_attribute: 1
      weight_decay: 1.0e-01
      loss: L1
      log_gradient: false
  frossen:
    check_val_every_n_epoch: 10
    epoker: 300
    steps: -1
    gradient_clipping: null
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 5.0e-03
      step_size: 1
      ønsket_lr: 5.0e-03
      opvarmningsperiode: 1
      predicted_attribute: 1
      weight_decay: 1.0e-06
      loss: L1
      frossen_opvarmningsperiode: null
      log_gradient: false
rygradtype: visnet
udgaver:
  - uden
temperaturer:
  - frossen
seeds:
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
run_baseline: false
gruppenavn: eksp4
data_path: s194255/afhandling/model-38styzwu:v0
kørselsid: 1