datasæt:
  batch_size: 128
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
  n_trin: 2
  spænd:
    - 10
    - 100
  val_reduced: true
downstream:
  check_val_every_n_epoch: 5
  epoker: 100
  min_delta: 0.1
  model:
    hovedtype: klogt
    gamma: 0.1
    lr: 1.0e-03
    step_size: 25
    ønsket_lr: 1.0e-03
    opvarmningsperiode: 1
    predicted_attribute: 1
  patience: 20
rygradtype: visnet
selvvejledt:
  check_val_every_n_epoch: 50
  epoker: 15
  hoved:
    atomref: null
    max_z: 100
    mean: 0.0
    reduce_op: sum
    std: 1.0
  min_delta: 0.001
  model:
    hovedtype: klogt
    gamma: 0.1
    lambdaer: null
    lr: 1.0e-06
    step_size: 500
    ønsket_lr: 1.0e-05
    opvarmningsperiode: 3
    noise_fra: -1
    noise_til: 1
    n_noise_trin: 2
    log_gradient: false
  patience: 20
udgaver:
  - med
  - uden
temperaturer:
  - frossen
