datasæt:
  batch_size: 128
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 2
  n_trin: 5
  spænd:
    - 30
    - 500
  val_reduced: true
  name: QM9
Downstream:
  optøet:
    check_val_every_n_epoch: 10
    epoker: 400
    steps: -1
    gradient_clipping: 1.0e-03
    model:
      hovedtype: klogt
      gamma: 1.0
      lr: 1.0e-04
      step_size: 1
      ønsket_lr: 1.0e-04
      opvarmningsperiode: 1
      predicted_attribute: 1
      weight_decay: 1.0e+05
      loss: L1
  frossen:
    check_val_every_n_epoch: 60
    epoker: 600
    steps: -1
    min_delta: 0.1
    gradient_clipping: null
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 4.0e-03
      step_size: 1
      ønsket_lr: 4.0e-03
      opvarmningsperiode: 1
      predicted_attribute: 1
      weight_decay: 1.0e-02
      loss: L1
    patience: 20
rygradtype: visnet
udgaver:
  - s194255/afhandling/model-av6l2023:v0
temperaturer:
  - optøet
seeds:
  - 399
run_baseline: false
gruppenavn: eksp2
data_path: s194255/afhandling/model-38styzwu:v0
kørselsid: 79