datasæt:
  batch_size: 32
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
downstream:
  epoker: 500
  hoved:
    num_layers: 1
    out_channels: 1
    reduce_op: sum
  min_delta: 0.0
  model:
    gamma: 0.1
    lr: 1.0e-03
    step_size: 10
  patience: 15
spænd:
  - 100
  - 2000
rygrad:
  cutoff: 5.0
  hidden_channels: 512
  lmax: 1
  maskeringsandel: null
  max_num_neighbors: 32
  max_z: 100
  num_heads: 8
  num_layers: 6
  num_rbf: 32
  trainable_rbf: false
  trainable_vecnorm: false
  vecnorm_type: null
  vertex: false
selvvejledt:
  epoker: 200
  hoved:
    atomref: null
    max_z: 100
    mean: 0.0
    reduce_op: sum
    std: 1.0
  min_delta: 0.001
  model:
    gamma: 0.1
    lambdaer: null
    lr: 1.0e-03
    step_size: 10
  patience: 20
trin: 5