datasæt:
  batch_size: 256
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 2
  n_trin: 5
  spænd:
    - 30
    - 500
  space_type: linspace
  val_reduced: true
  name: QM9
QM9:
  optøet:
    check_val_every_n_epoch: 10
    epoker: 300
    steps: -1
    gradient_clipping: null
    mixed: true
    model:
      hovedtype: klogt
      gamma: 0.98
      lr: 4.0e-03
      step_size: 1
      ønsket_lr: 2.5e-04
      opvarmningsperiode: 100
      frossen_opvarmningsperiode: 100
      predicted_attribute: 0
      weight_decay: 1.0e-00
      loss: L1
      log_gradient: false
  frossen:
    check_val_every_n_epoch: 10
    epoker: 300
    steps: -1
    gradient_clipping: null
    mixed: true
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 5.0e-03
      step_size: 1
      ønsket_lr: 5.0e-03
      opvarmningsperiode: 1
      predicted_attribute: 0
      weight_decay: 1.0e-08
      loss: L1
      frossen_opvarmningsperiode: null
      log_gradient: false
MD17:
  optøet:
    check_val_every_n_epoch: 10
    epoker: 300
    steps: -1
    gradient_clipping: null
    mixed: true
    model:
      hovedtype: klogt
      gamma: 0.98
      lr: 4.0e-03
      step_size: 1
      ønsket_lr: 2.5e-04
      opvarmningsperiode: 100
      frossen_opvarmningsperiode: 100
      weight_decay: 1.0e-06
      loss: L2
      log_gradient: false
rygradtype: visnet
udgaver:
  - s194255/afhandling/model-ez3wssr5:v0
  - uden
  - s194255/afhandling/model-yv2fp0x8:v0
  - s194255/afhandling/model-by37rvha:v0
  - s194255/afhandling/model-uvv3hn84:v144
temperaturer:
  - optøet
lag_liste:
  - null
seeds:
  - 665
  - 204
  - 505
  - 910
run_baseline: false
gruppenavn: eksp2
data_path: s194255/afhandling/model-5fn77j77:v0
kørselsid: 0