datasæt:
  batch_size: 256
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
  n_trin: 3
  spænd:
    - 10
    - 500
  val_reduced: true
Downstream:
  optøet:
    check_val_every_n_epoch: 80
    epoker: 800
    min_delta: 0.1
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 2.5e-03
      step_size: 1
      ønsket_lr: 2.5e-03
      opvarmningsperiode: 1
      predicted_attribute: 1
      weight_decay: 1.0e-02
    patience: 20
    seed: 42
  frossen:
    check_val_every_n_epoch: 40
    epoker: 400
    min_delta: 0.1
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 1.0e-02
      step_size: 1
      ønsket_lr: 1.0e-02
      opvarmningsperiode: 1
      predicted_attribute: 1
      weight_decay: 1.0e-02
    patience: 20
    seed: 0
rygradtype: visnet
udgaver:
  - uden
temperaturer:
  - frossen
run_baseline: false
qm9_path: s194255/afhandling/model-38styzwu:v0
kørselsid: 5
