datasæt:
  batch_size: 256
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
Downstream:
  variant1:
    check_val_every_n_epoch: 80
    epoker: 100
    min_delta: 0.1
    model:
      hovedtype: klogt
      gamma: 0.95
      lr: 1.0e-04
      step_size: 1
      ønsket_lr: 1.0e-04
      opvarmningsperiode: 1
      predicted_attribute: 1
    patience: 20
    seed: 42
rygradtype: visnet