datasæt:
  batch_size: 128
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 2
  n_trin: 5
  spænd:
    - 30
    - 500
  val_reduced: false
Downstream:
  optøet:
    check_val_every_n_epoch: 60
    epoker: 600
    min_delta: 0.1
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 5.0e-04
      step_size: 1
      ønsket_lr: 5.0e-04
      opvarmningsperiode: 1
      predicted_attribute: 1
      weight_decay: 1.0e-02
    patience: 20
  frossen:
    check_val_every_n_epoch: 60
    epoker: 600
    min_delta: 0.1
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 4.0e-03
      step_size: 1
      ønsket_lr: 4.0e-03
      opvarmningsperiode: 1
      predicted_attribute: 1
      weight_decay: 1.0e-02
    patience: 20
rygradtype: visnet
udgaver:
  - s194255/afhandling/model-zu71emmm:v0
temperaturer:
  - optøet
seeds:
  - 1
run_baseline: false
gruppenavn: eksp2
qm9_path: s194255/afhandling/model-38styzwu:v0
kørselsid: 60