debug: False
delmængdestørrelse: 1.0
fordeling: [0.85, 0.0125, 0.085, 0.0125, 0.04]
batch_size: 32
num_workers: 4
epoker_selvtræn: 20
epoker_efterfølgende: 5
frys_rygrad: True
lr: 0.00001
step_size: 20
gamma: 0.5
lambdaer: null