datasæt:
  batch_size: 32
  debug: true
  delmængdestørrelse: 1.0
  num_workers: 0
downstream:
  epoker: 1
  hoved:
    num_layers: 4
    out_channels: 1
    reduce_op: sum
  min_delta: 0.1
  model:
    gamma: 0.1
    lr: 1.0e-03
    step_size: 10
    max_lr: 1.0e-03
    warmup_period: 10
  patience: 5
spænd:
  - 100
  - 2000
rygrad:
  cutoff: 5.0
  hidden_channels: 8
  lmax: 1
  maskeringsandel: null
  max_num_neighbors: 32
  max_z: 100
  num_heads: 8
  num_layers: 6
  num_rbf: 32
  trainable_rbf: false
  trainable_vecnorm: false
  vecnorm_type: null
  vertex: false
selvvejledt:
  epoker: 50
  hoved:
    atomref: null
    max_z: 100
    mean: 0.0
    reduce_op: sum
    std: 1.0
  min_delta: 0.001
  model:
    gamma: 0.1
    lambdaer: null
    lr: 1.0e-05
    step_size: 10
    max_lr: 1.0e-03
    warmup_period: 10
  patience: 100
trin: 1