datasæt:
  batch_size: 512
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
  n_trin: 5
  spænd:
    - 10
    - 2000
  val_reduced: true
downstream:
  check_val_every_n_epoch: 5
  epoker: 100
  min_delta: 0.1
  model:
    hovedtype: klogt
    gamma: 0.99
    lr: 1.0e-03
    step_size: 1
    ønsket_lr: 1.0e-03
    opvarmningsperiode: 1
    predicted_attribute: 1
  patience: 20
rygradtype: visnet
selvvejledt:
  check_val_every_n_epoch: 1
  epoker: 50
  min_delta: 0.001
  model:
    hovedtype: klogt
    gamma: 0.1
    lambdaer:
      lokalt: 1000
      globalt: 1
    lr: 1.0e-08
    step_size: 15
    ønsket_lr: 1.0e-06
    opvarmningsperiode: 3
    noise_fra: -2
    noise_til: 1
    n_noise_trin: 10
    log_gradient: false
  patience: 20
udgaver:
  - uden
  - med
temperaturer:
  - optøet
selv_ckpt_path: s194255/afhandling/model-4ci6vjyd:v0
kørselsid: null
