datasæt:
  batch_size: 300
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 2
  n_trin: 1
  spænd:
    - 265
    - 265
  space_type: linspace
  val_reduced: true
  name: MD17
QM9:
  optøet:
    check_val_every_n_epoch: 10
    epoker: 300
    steps: -1
    gradient_clipping: null
    mixed: true
    model:
      hovedtype: klogt
      gamma: 0.98
      lr: 4.0e-03
      step_size: 1
      ønsket_lr: 2.5e-04
      opvarmningsperiode: 100
      frossen_opvarmningsperiode: 100
      predicted_attribute: 0
      weight_decay: 1.0e-00
      loss: L1
      log_gradient: false
  frossen:
    check_val_every_n_epoch: 10
    epoker: 300
    steps: -1
    gradient_clipping: null
    mixed: true
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 5.0e-03
      step_size: 1
      ønsket_lr: 5.0e-03
      opvarmningsperiode: 1
      predicted_attribute: 0
      weight_decay: 1.0e-08
      loss: L1
      frossen_opvarmningsperiode: null
      log_gradient: false
MD17:
  optøet:
    check_val_every_n_epoch: 10
    epoker: 1000
    steps: -1
    gradient_clipping: null
    mixed: true
    model:
      hovedtype: klogt
      gamma: 0.99
      lr: 1.0e-02
      step_size: 1
      ønsket_lr: 2.0e-4
      opvarmningsperiode: 50
      frossen_opvarmningsperiode: 50
      weight_decay: 1.0e-6
      loss: L2
      log_gradient: false
      predicted_attribute: energy
rygradtype: visnet
udgaver:
  - uden
temperaturer:
  - optøet
lag_liste:
  - null
seeds: 1
kaos:
  - false
run_baseline: false
gruppenavn: eksp2-md17
data_path: s194255/afhandling/model-hd4qrb57:v0
kørselsid: 1