datasæt:
  batch_size: 200
  debug: false
  delmængdestørrelse: 1.0
  num_workers: 4
  n_trin: 3
  spænd:
    - 500
    - 5000
  val_reduced: false
  name: QM9
rygradtype: visnet
Selvvejledt:
  QM9:
    check_val_every_n_epoch: 1
    log_every_n_steps: 10
    epoker: 150
    model:
      hovedtype: klogt
      gamma: 0.99
      lambdaer:
        lokalt: 100
        globalt: 20
      lr: 1.0e-04
      step_size: 1
      ønsket_lr: 1.0e-04
      opvarmningsperiode: 1
      noise_fra: -2
      noise_til: -0
      n_noise_trin: 50
      log_gradient: false
      weight_decay: 1.0e-7
  MD17:
    check_val_every_n_epoch: 1
    log_every_n_steps: 10
    epoker: 15
    min_delta: 0.001
    model:
      hovedtype: klogt_reg
      gamma: 0.99
      lambdaer:
        lokalt: 100
        globalt: 0
      lr: 3.0e-05
      step_size: 1
      ønsket_lr: 3.0e-05
      opvarmningsperiode: 1
      noise_fra: -2
      noise_til: 1
      n_noise_trin: 50
      log_gradient: false
      weight_decay: 1.0e-2
    patience: 20
SelvvejledtQM9:
  variant1:
    epoker: 100
    model:
      hovedtype: klogt
      gamma: 0.97
      lr: 0.25e-03
      step_size: 1
      ønsket_lr: 0.25e-03
      opvarmningsperiode: 1
      predicted_attribute: 1
      weight_decay: 1.0e-03
      loss: L1
    seed: 42
qm9_path: s194255/afhandling/model-5fn77j77:v0
modelklasse: Selvvejledt
ckpt: null