lmax: 1
vecnorm_type: null
trainable_vecnorm: false
num_heads: 8
num_layers: 6
num_rbf: 32
trainable_rbf: false
cutoff: 5.0
max_num_neighbors: 32
vertex: false
hidden_channels: 16
max_z: 100
maskeringsandel: null